preload = /home/vzkz/wallpaper/wallpaper_blue.jpg
preload = /home/vzkz/wallpaper/wallpaper_tetris.png
preload = /home/vzkz/wallpaper/waves.png

wallpaper = ,/home/vzkz/wallpaper/wallpaper_tetris.png
#wallpaper = ,/home/vzkz/wallpaper/wallpaper_tetris.png

