import = [
    "~/.config/alacritty/themes/themes/blood_moon.toml"
]

[window]

opacity = 0.9

padding.x = 10
padding.y = 10

dimensions.columns = 110
dimensions.lines= 30

position.x = 300
position.y = 200


decorations = "none"
decorations_theme_variant = "Dark" # "Light"

startup_mode = "maximized"


[font]

normal.family = "FiraCode Nerd Font"
bold.family = "FiraCode Nerd Font"
italic.family = "FiraCode Nerd Font"
bold_italic.family = "FiraCode Nerd Font"

size = 15.0

